apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongoDB
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/multi-cloud-demo.git
    targetRevision: main
    path: resources/helm-charts/helm-propagation
    values: |
      clusters:
        - demo-eks-cluster
        - demo-gke-cluster
      helm:
        - chart: psmdb-operator
          repo: https://percona.github.io/percona-helm-charts/
          version: 1.15.0
        - chart: psmdb-db
          repo: https://percona.github.io/percona-helm-charts/
          version: 1.15.0

  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3
