apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachDB
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/multi-cloud-demo.git
    targetRevision: main
    path: resources/helm-charts/helm-propagation
    values: |
      clusters:
        - demo-eks-cluster
        - demo-gke-cluster
      helm:
        - chart: cockroachdb
          repo: https://charts.cockroachdb.com/
          version: 23.1.12

  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3
