apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-helm-provider
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: aws-demo-cluster-kubeconfig
      namespace: crossplane-system
    source: Secret
