clusters:
  - demo-eks-cluster
  - demo-gke-cluster

helm:
  - chart: psmdb-operator
    repo: https://percona.github.io/percona-helm-charts/
    version: 1.15.0
  - chart: psmdb-db
    repo: https://percona.github.io/percona-helm-charts/
    version: 1.15.0
