apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-helm-provider
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: gcp-demo-cluster-kubeconfig
      namespace: crossplane-system
    source: Secret
