# harbor-propagation-policy-aws.yaml
apiVersion: core.karmada.io/v1alpha1
kind: KarmadaPropagationPolicy
metadata:
  name: harbor-replication-policy-aws
spec:
  template:
    spec:
      placement:
        clusterAffinity:
          clusterNames:
            - demo-eks-cluster
      providerRef:
        name: helm
      resources:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: harbor-chart
        spec:
          releaseName: harbor
          chart: "harbor/harbor"
          version: "latest"
          valuesContent: |-
            # Customize values here for AWS cluster
            harbor:
              expose:
                ingress:
                  host: "aws-harbor.example.com"
            replication:
              enabled: true
              endpoint: "https://gcp-harbor.example.com"
              username: "<replication-username>"
              password: "<replication-password>"

---

apiVersion: core.karmada.io/v1alpha1
kind: KarmadaPropagationPolicy
metadata:
  name: harbor-replication-policy-gcp
spec:
  template:
    spec:
      placement:
        clusterAffinity:
          clusterNames:
            - demo-gke-cluster
      providerRef:
        name: helm
      resources:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: harbor-chart
        spec:
          releaseName: harbor
          chart: "harbor/harbor"
          version: "latest"
          valuesContent: |-
            # Customize values here for GCP cluster
            harbor:
              expose:
                ingress:
                  host: "gcp-harbor.example.com"
            replication:
              enabled: true
              endpoint: "https://aws-harbor.example.com"
              username: "<replication-username>"
              password: "<replication-password>"
