apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/multi-cloud-demo.git
    targetRevision: main
    path: resources/helm-charts/helm-propagation
    values: |
      clusters:
        - demo-eks-cluster
        - demo-gke-cluster
      helm:
        - chart: harbor
          repo: https://helm.goharbor.io
          version: 1.13.1
          overrideRules:
            - targetCluster:
                clusterNames:
                  - demo-eks-cluster
              overriders:
                plaintext:
                  - path: "/spec/values"
                    operator: add
                    value:
                      harbor:
                        expose:
                          ingress:
                            host: "aws-harbor.example.com"
                      replication:
                        enabled: true
                        endpoint: "https://gcp-harbor.example.com"
                        username: "<replication-username>"
                        password: "<replication-password>"
            - targetCluster:
                clusterNames:
                  - demo-gke-cluster
              overriders:
                plaintext:
                  - path: "/spec/values"
                    operator: add
                    value:
                      harbor:
                        expose:
                          ingress:
                            host: "gcp-harbor.example.com"
                      replication:
                        enabled: true
                        endpoint: "https://aws-harbor.example.com"
                        username: "<replication-username>"
                        password: "<replication-password>"

  destination:
    server: https://kubernetes.default.svc
    namespace: harbour

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3
