{{- range .Values.secret }}

apiVersion: core.karmada.io/v1alpha1
kind: KarmadaPropagationPolicy
metadata:
  name: {{ .name }}-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      name: {{ .name }}
      namespace: {{ .namespace }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- $.Values.clusters | toYaml | nindent 8 }}
        {{- with .clusters }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}

{{- end }}
