apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-config
spec:
  projectID: trial-404919
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-provider-secret
      key: credentials
