apiVersion: core.karmada.io/v1alpha1
kind: KarmadaPropagationPolicy
metadata:
  name: cockroachdb-replication-policy
spec:
  template:
    spec:
      placement:
        clusterAffinity:
          clusterNames:
            {{- .Values.clusters | toYaml | nindent 12 }}
      providerRef:
        name: helm
      resources:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cockroachdb-chart
        spec:
          chart: cockroachdb
          repo: https://charts.cockroachdb.com/
          version: 23.1.12
          valuesContent: |-
            test: true
