apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karmada
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://raw.githubusercontent.com/karmada-io/karmada/master/charts
    targetRevision:  1.7.1
    chart: karmada
    helm:
      values: |
        test: value

  destination:
    server: https://kubernetes.default.svc
    namespace: karmada-system

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3
