apiVersion: core.karmada.io/v1alpha1
kind: KarmadaPropagationPolicy
metadata:
  name: mongodb--operator-replication-policy
spec:
  template:
    spec:
      placement:
        clusterAffinity:
          clusterNames:
            {{- .Values.clusters | toYaml | nindent 12 }}
      providerRef:
        name: helm
      resources:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: mongodb-chart
        spec:
          chart: psmdb-operator
          repo: https://percona.github.io/percona-helm-charts/
          version: 1.15.0
          valuesContent: |-
            test: true
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: mongodb-chart
        spec:
          chart: psmdb-db
          repo: https://percona.github.io/percona-helm-charts/
          version: 1.15.0
          valuesContent: |-
            test: true
